# To get started:
#
# pip install mkdocs
# pip install mkdocs-material
# Or just see the README
#
# ----------------------------------------------------------------------
site_name: DART Documentation
theme: material
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
repo_url:  https://github.com/APTrust/dart
nav:
  - Home: index.md
  - DART 2:
    - Home: dart2/index.md
    - Videos: dart2/videos.md
    - Download: dart2/download.md
    - For Users:
        - dart2/users/getting_started.md
        - Jobs:
            - dart2/users/jobs/index.md
            - dart2/users/jobs/list.md
            - dart2/users/jobs/files.md
            - dart2/users/jobs/packaging.md
            - dart2/users/jobs/metadata.md
            - dart2/users/jobs/upload.md
            - dart2/users/jobs/run.md
            - dart2/users/jobs/delete.md
            - dart2/users/jobs/validation.md
            - dart2/users/jobs/troubleshooting.md
        - Workflows:
            - dart2/users/workflows/index.md
            - dart2/users/workflows/job_params.md
            - dart2/users/workflows/batch_jobs.md
        - Settings:
            - dart2/users/settings/index.md
            - dart2/users/settings/app_settings.md
            - dart2/users/settings/internal_settings.md
            - dart2/users/settings/remote_repositories.md
            - dart2/users/settings/storage_services.md
            - dart2/users/settings/plugins.md
            - dart2/users/settings/export.md
            - dart2/users/settings/import.md
        - Dashboard: dart2/users/dashboard.md
        - BagIt Profiles:
            - dart2/users/bagit/index.md
            - dart2/users/bagit/importing.md
            - dart2/users/bagit/exporting.md
            - dart2/users/bagit/creating.md
            - dart2/users/bagit/customizing.md
        - Command Line Reference: dart2/users/command_line.md
        - Scripting with DART: dart2/users/scripting.md
        - Logs: dart2/users/logs.md
        - FAQ: dart2/users/faq.md
    - For Developers:
        - dart2/developers/index.md
        - Architecture: dart2/developers/architecture.md
        - Data Storage: dart2/developers/data_storage.md
        - Job Flow: dart2/developers/job_flow.md
        - Building: dart2/developers/building.md
        - Testing: dart2/developers/testing.md
        - Documenting: dart2/developers/documenting.md
        - Logging: dart2/developers/logging.md
        - Plugins:
            - dart2/developers/plugins/index.md
            - Plugin Manager: dart2/developers/plugins/manager.md
            - Format Readers: dart2/developers/plugins/format_readers.md
            - Format Writers: dart2/developers/plugins/format_writers.md
            - Network Clients: dart2/developers/plugins/network_clients.md
            - Repository Clients: dart2/developers/plugins/repo_clients.md
  - DART 3:
    - Home: dart3/index.md
    - Download: dart3/download.md
    - For Users:
        - dart3/users/getting_started.md
        - Jobs:
            - dart3/users/jobs/index.md
            - dart3/users/jobs/list.md
            - dart3/users/jobs/artifacts.md
            - dart3/users/jobs/files.md
            - dart3/users/jobs/packaging.md
            - dart3/users/jobs/metadata.md
            - dart3/users/jobs/upload.md
            - dart3/users/jobs/run.md
            - dart3/users/jobs/delete.md
            - dart3/users/jobs/validation.md
            - dart3/users/jobs/troubleshooting.md
        - Workflows:
            - dart3/users/workflows/index.md
            - dart3/users/workflows/job_params.md
            - dart3/users/workflows/batch_jobs.md
        - Settings:
            - dart3/users/settings/index.md
            - dart3/users/settings/app_settings.md
            - dart3/users/settings/internal_settings.md
            - dart3/users/settings/remote_repositories.md
            - dart3/users/settings/storage_services.md
            - dart3/users/settings/export.md
            - dart3/users/settings/import.md
        - Dashboard: dart3/users/dashboard.md
        - BagIt Profiles:
            - dart3/users/bagit/index.md
            - dart3/users/bagit/importing.md
            - dart3/users/bagit/exporting.md
            - dart3/users/bagit/creating.md
            - dart3/users/bagit/customizing.md
        - Logs: dart3/users/logs.md
        - FAQ: dart3/users/faq.md
  - Dart Runner: runner/index.md
